#!/usr/bin/expect

set password "password_baru"
set username "nama_pengguna"

spawn passwd $username
expect {
    "New password: " {
        send -- "$password\r"
        expect {
            "Retype new password: " {
                send -- "$password\r"
                expect eof
            }
            timeout {
                puts "Timeout!"
                exit 1
            }
        }
    }
    timeout {
        puts "Timeout!"
        exit 1
    }
    eof {
        puts "Proses selesai!"
    }
}
